#!/usr/bin/env python3
"""Generate the DourMouse app icon (1024x1024 RGBA PNG) with pure stdlib.

Draws a deep-navy rounded square with a soft radial glow and the brand's
"double diamond" (◈) mark in cyan. Supersampled 2x2 for anti-aliasing,
proper alpha-over compositing.

Usage: python3 make_icon.py [out.png]

REBUILDING THE .app BUNDLE (if it is ever regenerated by Script Editor,
which would clobber the branding):

  1. Icon: python3 make_icon.py master.png, then sips all 10 iconset
     sizes, iconutil -c icns, copy into Contents/Resources, and set
     CFBundleIconFile -> DourMouse in Info.plist.
  2. Applet: osacompile -o .../Scripts/main.scpt /tmp/dourmouse_applet.applescript
     (the no-Terminal on run + reopen handler).
  3. Plist: CFBundleName/DisplayName "DourMouse", id com.dourmouse.desktop,
     version, NSHighResolutionCapable, keep the dourmouse:// scheme.
  4. Sign (best-effort; unsigned launches fine locally):
     codesign --force -s - dourmouse.app
"""
import struct
import sys
import zlib
from math import exp

SIZE = 1024
SS = 2  # supersample factor
# Anti-aliasing ramp width in unit space (1 unit = SIZE/2 px).
AA = 4.0 / (SIZE / 2.0)


def _write_png(path: str, pixels: bytes, width: int, height: int) -> None:
    def chunk(tag: bytes, data: bytes) -> bytes:
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    raw = b""
    for y in range(height):
        raw += b"\x00" + pixels[y * width * 4:(y + 1) * width * 4]
    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9))
    png += chunk(b"IEND", b"")
    with open(path, "wb") as fh:
        fh.write(png)


def _smooth(edge: float) -> float:
    """Smoothstep-ish 0..1 coverage given a signed distance to an edge."""
    x = max(-1.0, min(1.0, edge))
    return x * 0.5 + 0.5


def _rounded_rect_cov(x: float, y: float, r: float) -> float:
    """Coverage of a full-size rounded square at (x,y) in unit space [-1,1]."""
    hw, hh = 1.0, 1.0
    rx, ry = r / SIZE, r / SIZE
    dx = max(abs(x) - (hw - rx), 0.0)
    dy = max(abs(y) - (hh - ry), 0.0)
    d = (dx * dx + dy * dy) ** 0.5 - rx
    return _smooth(-d / AA)


def _diamond_dist(x: float, y: float, w: float, h: float) -> float:
    """Signed distance to the boundary of an axis-aligned diamond."""
    return (abs(x) / w + abs(y) / h - 1.0) * min(w, h)


def _over(src, dst):
    """Straight-alpha 'source over' composite. Each is (r, g, b, a) 0..1."""
    sa = src[3]
    da = dst[3] * (1.0 - sa)
    a = sa + da
    if a <= 0.0:
        return (0.0, 0.0, 0.0, 0.0)
    r = (src[0] * sa + dst[0] * da) / a
    g = (src[1] * sa + dst[1] * da) / a
    b = (src[2] * sa + dst[2] * da) / a
    return (r, g, b, a)


def main() -> None:
    global SIZE  # rendering size (defaults to 1024)
    out = sys.argv[1] if len(sys.argv) > 1 else "icon_master.png"
    # --opaque: fill the transparent rounded-rect corners with the navy
    # background (iOS apple-touch-icon must be opaque — transparent corners
    # render as black behind the home-screen mask).
    opaque = "--opaque" in sys.argv
    # --size N: render directly at N x N instead of 1024 (crisp icons at
    # any size; the drawing geometry is all relative to SIZE). Used for the
    # PWA icons — avoids sips, whose PNG output has proven unreliable here.
    if "--size" in sys.argv:
        try:
            SIZE = int(sys.argv[sys.argv.index("--size") + 1])
        except (ValueError, IndexError):
            pass
    px = bytearray(SIZE * SIZE * 4)

    bg_top = (10, 16, 38)
    bg_bot = (23, 33, 66)
    glow = (0, 216, 255)
    ring = (64, 216, 255)
    core = (226, 250, 255)

    outer_w, outer_h = 0.335, 0.335
    inner_w, inner_h = 0.135, 0.135

    for y in range(SIZE):
        for x in range(SIZE):
            r_acc = g_acc = b_acc = a_acc = 0.0
            for sy in range(SS):
                for sx in range(SS):
                    ux = (x + (sx + 0.5) / SS) / SIZE * 2.0 - 1.0
                    uy = (y + (sy + 0.5) / SS) / SIZE * 2.0 - 1.0

                    radius_px = 178.0 * SIZE / 1024.0  # scale the corner radius
                    rect = _rounded_rect_cov(ux, uy, radius_px)
                    if opaque:
                        rect = max(rect, 1.0)  # fill the corners too
                    if rect <= 0.0:
                        continue

                    t = (uy + 1.0) / 2.0
                    vig = 1.0 - 0.35 * max(0.0, (ux * ux + uy * uy) ** 0.5 - 0.55)
                    # All colour math is 0..1; palettes above are 0..255.
                    br = (bg_top[0] + (bg_bot[0] - bg_top[0]) * t) / 255.0 * vig
                    bg = (bg_top[1] + (bg_bot[1] - bg_top[1]) * t) / 255.0 * vig
                    bb = (bg_top[2] + (bg_bot[2] - bg_top[2]) * t) / 255.0 * vig

                    # Base: the rounded square, edge-AA'd by its coverage.
                    base = (br, bg, bb, rect)

                    # Radial glow behind the mark (additive light bleed).
                    d_glow = (ux * ux + uy * uy) ** 0.5
                    glow_a = 0.85 * exp(-max(0.0, d_glow - 0.18) ** 2 / 0.055)
                    base = (base[0] + glow[0] / 255.0 * glow_a,
                            base[1] + glow[1] / 255.0 * glow_a,
                            base[2] + glow[2] / 255.0 * glow_a, base[3])

                    # Outer diamond ring band.
                    d_out = _diamond_dist(ux, uy, outer_w, outer_h)
                    d_in = _diamond_dist(ux, uy, inner_w, inner_h)
                    band_cov = _smooth(-d_out / AA) * _smooth(d_in / AA)
                    if band_cov > 0.0:
                        shade = 1.0 - 0.25 * max(0.0, (d_in - 0.02) / 0.12)
                        band = (ring[0] * shade / 255.0,
                                ring[1] * shade / 255.0,
                                ring[2] * shade / 255.0, band_cov)
                        base = _over(band, base)

                    # Inner diamond core.
                    core_cov = _smooth(-d_in / AA)
                    if core_cov > 0.0:
                        core_px = (core[0] / 255.0, core[1] / 255.0,
                                   core[2] / 255.0, core_cov)
                        base = _over(core_px, base)

                    r_acc += base[0]
                    g_acc += base[1]
                    b_acc += base[2]
                    a_acc += base[3] * 255.0

            n = SS * SS
            idx = (y * SIZE + x) * 4
            px[idx + 0] = max(0, min(255, int(r_acc / n * 255.0 + 0.5)))
            px[idx + 1] = max(0, min(255, int(g_acc / n * 255.0 + 0.5)))
            px[idx + 2] = max(0, min(255, int(b_acc / n * 255.0 + 0.5)))
            px[idx + 3] = max(0, min(255, int(min(1.0, a_acc / n) * 255.0 + 0.5)))

    _write_png(out, bytes(px), SIZE, SIZE)
    print(f"wrote {out} ({SIZE}x{SIZE})")


if __name__ == "__main__":
    main()
